apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cockpitApp.fullname" . }}
  labels:
    {{- include "cockpitApp.labels" . | nindent 4 }}
spec: 
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cockpitApp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cockpitApp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      #Der Init Container
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      

      containers:
      #PHP-fpm Container
        - name: php-fpm
          image: "{{ .Values.phpFpm.image.repository }}:{{ .Values.phpFpm.image.tag | default "latest" }}"
          imagePullPolicy: {{.Values.phpFpm.image.pullPolicy}}
          ports:
              - name: fpm
                containerPort: {{.Values.phpFpm.service.port}}

          {{- with .Values.phpFpm.volumeMounts}}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: app-env 


      #Nginx Container
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.port }}
              protocol: TCP

          {{- with .Values.nginx.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}



      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}